In [4]:
import pandas as pd

#docs = pd.read_excel('SMSSpamCollection.xls',header=None,names=['Class', 'SMS']) 
docs = pd.read_table('C:/Users/chaganti.babu/Documents/ML&AI/ML/Naive Bayes/Assignment/example_train.csv', header=None, names=['Class', 'sms'])

#classifier in column 1, sms in column 2.
docs.head()


Class  sms
0                                     Document,Class  NaN
1  Upgrad is a great educational institution.,edu...  NaN
2  Educational greatness depends on ethics,education  NaN
3  A story of great ethics and educational greatn...  NaN
4                    Sholey is a great cinema,cinema  NaN

In [2]:
# counting spam and ham instances
# df.column_name.value_counts() - gives no. of unique inputs in the columns

ham_spam=docs.Class.value_counts()
ham_spam

ham     4825
spam     747
Name: Class, dtype: int64

In [3]:
print("Spam % is ",(ham_spam[1]/float(ham_spam[0]+ham_spam[1]))*100)

Spam % is  13.406317300789663


In [4]:
# mapping labels to 0 and 1
docs['label'] = docs.Class.map({'ham':0, 'spam':1})

In [5]:
docs.head()

Class                                                sms  label
0   ham  Go until jurong point, crazy.. Available only ...      0
1   ham                      Ok lar... Joking wif u oni...      0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3   ham  U dun say so early hor... U c already then say...      0
4   ham  Nah I don't think he goes to usf, he lives aro...      0

In [6]:
X=docs.sms
y=docs.label

In [7]:
X = docs.sms
y = docs.label
print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [8]:
# splitting into test and train into default 75:25 ratio

from sklearn.model_selection  import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [9]:
X_train.head()

710     4mths half price Orange line rental & latest c...
3740                           Did you stitch his trouser
2711    Hope you enjoyed your new content. text stop t...
3155    Not heard from U4 a while. Call 4 rude chat pr...
3748    Ü neva tell me how i noe... I'm not at home in...
Name: sms, dtype: object

In [32]:
X_train.shape

(4179,)

In [34]:
X_test.shape

(1393,)

In [10]:
# vectorizing the sentences; removing stop words
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(stop_words='english')

In [11]:
vect.fit(X_train)
# X_train_dtm = vect.transform(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [12]:
# printing the vocabulary
vect.vocabulary_

{'problem': 5047,
 'gower': 2997,
 'cal': 1502,
 'some1': 5848,
 'opinions': 4614,
 'trusting': 6554,
 'playing': 4878,
 'fgkslpo': 2637,
 'weigh': 6924,
 'gumby': 3063,
 '〨ud': 7203,
 'library': 3824,
 'teaches': 6272,
 'charles': 1636,
 'munsters': 4343,
 'letter': 3817,
 'sportsx': 5956,
 'entitled': 2446,
 'wicklow': 6974,
 'soiree': 5841,
 '1hr': 318,
 'hanks': 3109,
 'goin': 2958,
 '2mrw': 395,
 'quote': 5154,
 'slowly': 5793,
 'working': 7062,
 'king': 3684,
 'hyde': 3329,
 'john': 3584,
 'catch': 1583,
 'asjesus': 1031,
 'usually': 6712,
 'thekingshead': 6352,
 'glad': 2936,
 'tram': 6514,
 'box245c2150pm': 1364,
 'akon': 864,
 'wasted': 6874,
 'cheers': 1662,
 'ques': 5141,
 'prix': 5041,
 '26': 363,
 'stairs': 5978,
 'notxt': 4514,
 'infra': 3429,
 'ideas': 3353,
 'frying': 2819,
 'sk38xh': 5757,
 'heehee': 3171,
 'hi': 3202,
 'ericsson': 2459,
 '4msgs': 508,
 'wait': 6834,
 'revision': 5372,
 'sherawat': 5652,
 '5ish': 544,
 'felt': 2628,
 'street': 6056,
 'jet': 3569,
 'ins

In [13]:
# transforming the train and test datasets
X_train_transformed = vect.transform(X_train)
X_test_transformed =vect.transform(X_test)

In [14]:
# note that the type is transformed matrix
print(type(X_train_transformed))
print(X_train_transformed)

<class 'scipy.sparse.csr.csr_matrix'>
  (0, 50)	1
  (0, 264)	1
  (0, 509)	1
  (0, 1527)	1
  (0, 1971)	1
  (0, 2780)	2
  (0, 3089)	1
  (0, 3763)	1
  (0, 3852)	1
  (0, 4248)	1
  (0, 4624)	1
  (0, 4626)	1
  (0, 4818)	1
  (0, 4822)	1
  (0, 5027)	1
  (0, 5310)	1
  (0, 6673)	1
  (1, 2169)	1
  (1, 6028)	1
  (1, 6545)	1
  (2, 98)	1
  (2, 563)	1
  (2, 1867)	1
  (2, 2436)	1
  (2, 3180)	1
  :	:
  (4176, 3879)	1
  (4176, 4417)	1
  (4176, 5229)	1
  (4176, 6191)	1
  (4176, 7134)	1
  (4177, 254)	1
  (4177, 307)	1
  (4177, 358)	1
  (4177, 831)	1
  (4177, 2046)	1
  (4177, 2704)	1
  (4177, 3585)	1
  (4177, 3623)	1
  (4177, 4130)	1
  (4177, 4315)	1
  (4177, 4771)	1
  (4177, 5234)	1
  (4177, 5321)	1
  (4177, 5487)	1
  (4177, 5620)	1
  (4177, 6321)	1
  (4177, 6374)	1
  (4177, 6453)	1
  (4178, 1643)	1
  (4178, 5817)	1


In [15]:
# training the NB model and making predictions
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

# fit
mnb.fit(X_train_transformed,y_train)

# predict class
y_pred_class = mnb.predict(X_test_transformed)

# predict probabilities
y_pred_proba =mnb.predict_proba(X_test_transformed)


# printing the overall accuracy
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)


0.9877961234745154

In [16]:
# note that alpha=1 is used by default for smoothing
mnb

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [17]:
# confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[1201,    7],
       [  10,  175]], dtype=int64)

In [18]:
confusion = metrics.confusion_matrix(y_test, y_pred_class)
print(confusion)
#[row, column]
TN = confusion[0, 0]
FP = confusion[0, 1]
FN = confusion[1, 0]
TP = confusion[1, 1]

[[1201    7]
 [  10  175]]


In [19]:
sensitivity = TP / float(FN + TP)
print("sensitivity",sensitivity)

sensitivity 0.9459459459459459


In [20]:
specificity = TN / float(TN + FP)

print("specificity",specificity)

specificity 0.9942052980132451


In [21]:
precision = TP / float(TP + FP)

print("precision",precision)
print(metrics.precision_score(y_test, y_pred_class))

precision 0.9615384615384616
0.9615384615384616


In [22]:
print("precision",precision)
print("PRECISION SCORE :",metrics.precision_score(y_test, y_pred_class))
print("RECALL SCORE :", metrics.recall_score(y_test, y_pred_class))
print("F1 SCORE :",metrics.f1_score(y_test, y_pred_class))

precision 0.9615384615384616
PRECISION SCORE : 0.9615384615384616
RECALL SCORE : 0.9459459459459459
F1 SCORE : 0.9536784741144414


In [23]:
y_pred_class

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [24]:
y_pred_proba

array([[9.95239557e-01, 4.76044325e-03],
       [9.99852357e-01, 1.47642544e-04],
       [9.27878579e-01, 7.21214213e-02],
       ...,
       [9.99999671e-01, 3.28799076e-07],
       [3.72703622e-09, 9.99999996e-01],
       [9.99999985e-01, 1.46852511e-08]])