# Introduction to NumPy


The objectives of this section are:

* What is NumPy and it's advantage instead of using Python Lists,tuples, dictionaries etc
* Create NumPy arrays
* Indexing, iterating through NumPy arrays and  getting subsets
* Simple test to understand how faster NumPy is compared to Python datastructures

### What is NumPy?

NumPy is a library written for scientific computing and data analysis. It stands for numerical python.

The class of the NumPy is  ```ndarray```, which means **n-dimensional, homogenous** array. Homogenous here refers to all the elements in a numpy array are of **same data type** and it is typically numeric i.e. integer or float. 


In [2]:
# Import the numpy library
# np is an alias name. We can use any name apart from np
import numpy as np

In [3]:
# Create a single dimension array(1-D) by using a list
# np.array() takes the python data structures like lists, tuples and convert it into an Array

single_dimension = np.array([6, 14, 58, 16, 3, 1])
print(single_dimension)
print(type(single_dimension))

[ 6 14 58 16  3  1]
<class 'numpy.ndarray'>


In [4]:
# Creating a 2-D array using two lists
two_dimensional = np.array([[5, 9, 14], [3, 6, 2]])
print(two_dimensional)

[[ 5  9 14]
 [ 3  6  2]]


The above array can be called as 2-dimensional array having two axes. Array has two lists(rows) and each row has three elements respectively. We can call these dimensions as **axes**.

In case of 2-Dimnsional arrays:
* ```axis = 0``` refers to the rows
* ```axis = 1``` refers to the columns

<img src="axes.png" style="width: 400px; height: 300px">

### Advantages of NumPy 

1. In NumPy array the data is stored in a homogeneous and contiguous block of memory, at a particular address in system memory  where as the items in lists are scattered across the system memory.

2. Knowing the address of the memory block and the data type, it is just simple arithmetic to loop over all items. There would be a significant overhead to do that in Python with a list.

In below example, we demonstrate how two lists of numbers are calculated the element-wise product. In the standard python list way we need to implement the map function with lambda expression , whereas in NumPy, we can directly multiply the arrays.

In [5]:
list_1 = [4, 2, 6, 3]
list_2 = [5, 8, 3, 9]

# the list way to do it is using the map function along with the lambda expression by passing two lists
multiply_lists = list(map(lambda x, y: x*y, list_1, list_2))
print(multiply_lists)


[20, 16, 18, 27]


In [7]:
# The numpy array way to do it: simply multiply the two arrays
array_1 = np.array(list_1)
array_2 = np.array(list_2)

array_3 = array_1*array_2
print(array_3)
print(type(array_3))

[20 16 18 27]
<class 'numpy.ndarray'>


As you can see, the numpy way is clearly more concise.

Even simple mathematical operations on lists require for loops, unlike with arrays. For example, to calculate the square of every number in a list:

In [8]:
# Square every element in a lst
squared_list = [x**2 for x in list_1]

# Square a numpy array
squared_array = array_1**2

print(squared_list)
print(squared_array)

[16, 4, 36, 9]
[16  4 36  9]


So far we have discussed about 1-D arrays. We may need to work with 2-D arrays (rowsXcolumns). In case of lists, we need to store matrices as lists of lists and loop through them. Where as in NumPy, we can directly multiply the matrices.

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, below are the common appraoches:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 


In [8]:
# Convert lists or tuples to arrays using np.array()
# Note that np.array(2, 5, 6, 7) will throw an error - you need to pass a list or a tuple
array_from_list = np.array([2, 5, 6, 7]) 
array_from_tuple = np.array((4, 5, 8, 9))

print(array_from_list)
print(array_from_tuple)

[2 5 6 7]
[4 5 8 9]


The other common way is to initialise arrays. You do this when you know the size of the array beforehand.

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [9]:
# Tip: Use help to see the syntax when required
help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    zeros, ones_like
    
    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])
    
    >>> np.ones((5,), dtype=np.int)
    array([1, 1, 1, 1, 1])
    
    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])
    
    >>> s = (2,2)
    >>> np.ones(s)
   

In [10]:
# Creating a 5 x 3 array of ones
np.ones((5, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
# Notice that, by default, numpy creates data type = float64
# Can provide dtype explicitly using dtype
np.ones((5, 3), dtype = np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
# Creating array of zeros
np.zeros(4, dtype = np.int)

array([0, 0, 0, 0])

In [13]:
# Array of random numbers
np.random.random([3, 4])

array([[ 0.65054112,  0.77627157,  0.86829133,  0.56742478],
       [ 0.73805244,  0.09720623,  0.41031352,  0.72710595],
       [ 0.19143811,  0.59561384,  0.01178463,  0.56789889]])

In [14]:
# np.arange()
# np.arange() is the numpy equivalent of range()
# Notice that 10 is included, 100 is not, as in standard python lists

# From 10 to 100 with a step of 5
numbers = np.arange(10, 100, 5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [15]:
# np.linspace()
# Sometimes, you know the length of the array, not the step size

# Array of length 25 between 15 and 18
np.linspace(15, 18, 25)

array([ 15.   ,  15.125,  15.25 ,  15.375,  15.5  ,  15.625,  15.75 ,
        15.875,  16.   ,  16.125,  16.25 ,  16.375,  16.5  ,  16.625,
        16.75 ,  16.875,  17.   ,  17.125,  17.25 ,  17.375,  17.5  ,
        17.625,  17.75 ,  17.875,  18.   ])

### Inspect the Structure and Content of Arrays

It is helpful to inspect the structure of numpy arrays, especially while working with large arrays. Some attributes of numpy arrays are:
* ```shape```: Shape of array (n x m)
* ```dtype```: data type (int, float etc.)
* ```ndim```: Number of dimensions (or axes)
* ```itemsize```: Memory used by each array elememnt in bytes


Let's say you are working with a moderately large array of size 1000 x 300. First, you would want to wrap your head around the basic shape and size of the array. 

In [16]:
# Initialising a random 1000 x 300 array
rand_array = np.random.random((1000, 300))

# Print the first row
print(rand_array[1, ])

[ 0.55412106  0.54571034  0.67656807  0.6381752   0.54967476  0.31890341
  0.29984374  0.24586699  0.29819043  0.29221088  0.12420063  0.06669798
  0.1827458   0.4389338   0.76450338  0.85016549  0.92799268  0.11499827
  0.50575161  0.59894106  0.78978273  0.7766561   0.5067567   0.15736428
  0.09969272  0.94432416  0.24422035  0.17452004  0.85108746  0.04593323
  0.67754748  0.53721925  0.20577505  0.12535662  0.16732805  0.50149549
  0.51833773  0.05397893  0.66861373  0.08863367  0.53558428  0.19957231
  0.01727665  0.97761211  0.80924291  0.34190059  0.83552391  0.47360201
  0.4664945   0.03350398  0.72178958  0.24441449  0.19466602  0.13039931
  0.23415935  0.06908054  0.46387589  0.43260427  0.07898703  0.49867763
  0.86287     0.3317592   0.17515919  0.95373435  0.91598295  0.24724186
  0.63144363  0.45995238  0.35122126  0.55948942  0.30937341  0.36670186
  0.05076366  0.48007449  0.92770376  0.55658022  0.38334219  0.99055412
  0.6727068   0.25863243  0.1361599   0.89487361  0

In [17]:
# Inspecting shape, dtype, ndim and itemsize
print("Shape: {}".format(rand_array.shape))
print("dtype: {}".format(rand_array.dtype))
print("Dimensions: {}".format(rand_array.ndim))
print("Item size: {}".format(rand_array.itemsize))

Shape: (1000, 300)
dtype: float64
Dimensions: 2
Item size: 8


Reading 3-D arrays is not very obvious, because we can only print maximum two dimensions on paper, and thus they are printed according to a specific convention. Printing higher dimensional arrays follows the following conventions:
* The last axis is printed from left to right
* The second-to-last axis is printed from top to bottom
* The other axes are also printed top-to-bottom, with each slice separated by another using an empty line 

Let's see some examples.

In [18]:
# Creating a 3-D array
# reshape() simply reshapes a 1-D array 
array_3d = np.arange(24).reshape(2, 4, 3)
print(array_3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


* The last axis has 4 elements, and is printed from left to right.
* The second last has 3, and is printed top to bottom
* The other axis has 2, and is printed in the two separated blocks

<img src="N-Dimensional.png" style="width: 400px; height: 300px">

### Subset, Slice, Index and Iterate through Arrays

For **one-dimensional arrays**, indexing, slicing etc. is **similar to python lists** - indexing starts at 0.

In [19]:
# Indexing and slicing one dimensional arrays
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
# Third element
print(array_1d[2])

# Specific elements
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
print(array_1d[[2, 5, 6]])

# Slice third element onwards
print(array_1d[2:])

# Slice first three elements
print(array_1d[:3])

# Slice third to seventh elements
print(array_1d[2:7])

# Subset starting 0 at increment of 2 
print(array_1d[0::2])

2
[2 5 6]
[2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]


In [21]:
# Iterations are also similar to lists
for i in array_1d:
    print(i**2)

0
1
4
9
16
25
36
49
64
81


**Multidimensional arrays** are indexed using as many indices as the number of dimensions or axes. For instance, to index a 2-D array, you need two indices - ```array[x, y]```. 

Each axes has an index starting at 0. The following figure shows the axes and their indices for a 2-D array.

<img src="2_d_array.png" style="width: 350px; height: 300px">


In [22]:
# Creating a 2-D array
array_2d = np.array([[2, 5, 7, 5], [4, 6, 8, 10], [10, 12, 15, 19]])
print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [23]:
# Third row second column
print(array_2d[2, 1])

12


In [24]:
# Slicing the second row, and all columns
# Notice that the resultant is itself a 1-D array
print(array_2d[1, :])
print(type(array_2d[1, :]))

[ 4  6  8 10]
<class 'numpy.ndarray'>


In [25]:
# Slicing all rows and the third column
print(array_2d[:, 2])

[ 7  8 15]


In [26]:
# Slicing all rows and the first three columns
print(array_2d[:, :3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


**Iterating on 2-D arrays** is done with respect to the first axis (which is row, the second axis is column). 

In [32]:
# Iterating over 2-D arrays
for row in array_2d:
    #print(row)
    for x in row:
        print(x)

2
5
7
5
4
6
8
10
10
12
15
19


In [28]:
# Iterating over 3-D arrays: Done with respect to the first axis
array_3d = np.arange(24).reshape(2, 3, 4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [35]:
# Prints the two blocks
for row in array_3d:
    #print(row)
    for x in row:
        #print(x)
        for i in x:
            print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


### Compare Computation Times in NumPy and Standard Python Lists

We mentioned that the key advantages of numpy are convenience and speed of computation. 

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.   

Let's compare the computation times of arrays and lists for a simple task of calculating the element-wise product of numbers. 

In [37]:
## Comparing time taken for computation
list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

# list multiplication
import time

# store start time, time after computation, and take the difference
t0 = time.time()
product_list = list(map(lambda x, y: x*y, list_1, list_2))
t1 = time.time()
list_time = t1 - t0 
print(t1-t0)


# numpy array 
array_1 = np.array(list_1)
array_2 = np.array(list_2)

t0 = time.time()
array_3 = array_1*array_2
t1 = time.time()
numpy_time = t1 - t0

print(t1-t0)

print("The ratio of time taken is {}".format(list_time/numpy_time))

0.22699284553527832
0.00699615478515625
The ratio of time taken is 32.44537213740458


In this case, numpy is **an order of magnitude faster** than lists. This is with arrays of size in millions, but you may work on much larger arrays of sizes in order of billions. Then, the difference is even larger.

Some reasons for such difference in speed are:
* NumPy is written in C, which is basically being executed behind the scenes
* NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists


The following discussions demonstrate the differences in speeds of NumPy and standard python:
1. https://stackoverflow.com/questions/8385602/why-are-numpy-arrays-so-fast
2. https://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists
